version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/reminder-backend/:/var/www/symfony
    ports:
      - "9000:9000"
    networks:
      - reminder-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/reminder-frontend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - reminder-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nico@131415
      MYSQL_DATABASE: reminder
      MYSQL_USER: reminder
      MYSQL_PASSWORD: poople
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reminder-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: nico@131415
    networks:
      - reminder-network

networks:
  reminder-network:
    driver: bridge

volumes:
  mysql_data: